# Supabase credentials (DO NOT COMMIT THIS FILE)
SUPABASE_URL = "https://qvcygbetrphnasrobium.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2Y3lnYmV0cnBobmFzcm9iaXVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMDE1MDcsImV4cCI6MjA3OTU3NzUwN30.a3jZ4n88CxfK-KKgK7oM8rh3xkwSsfGrRolnv_iLKrw"
